### ISSUE TITLE
MVP to-do

### ISSUE THREAD

**Issue by martinpitt** [martinpitt/performance-graphs#1]
Features:
 - [x] Add disk I/O utilization [ @martinpitt ]
 - [x] Add network utilization  [ @martinpitt ]
 - [x] Dynamically update the graphs for new data [ @martinpitt ]
 - [x] Add more data (infinite scrolling or just button) at the bottom of page, or do paging to avoid rendering too much  [ @marusak ]
 - [x] Better normalization of unbounded values (determine maximum at runtime) [ @martinpitt ]
 - [x] Better spike detection [ @martinpitt ]

Code structure:
 - [x] Generalize the data arrays to an object
 - [x] Generalize spike detection for all metrics
 - [x] Fix wrong spikes at hour boundaries
 - [x] Generalize `load_hour()` and `<MetricsHour>` rendering for multiple hours
 - [x] Change data structures to keep original data for tooltips, and keep the interpretation separate [ @martinpitt ]

Design:
 - [x] Make stretched minutes easier to see -- rulers/tickmarks?
 - [x] Don't show horizontal rulers for empty minutes, or otherwise make data vs. no data sections stand apart [ @marusak ]
 - [x] Show spinner while loading more data
 - [x] Handle data gaps > 12 hours, when "Load more data" does not visibly do anything when you click it (ideally it should enumerate for which days it has data available)

Performance:
 - [x] Improve speed, current page hangs for a long time during loading
 - [x] Merge util+sat SVG and use a shared ruler [ @martinpitt ]

Error handling:
 - [x] Proper Empty State during loading
 - [x] Empty State if pcp is not available ("upsell") [ @marusak ]
 - [x] Check what happens without any data (cockpit-pcp installed, but pcp not enabled) → empty state [ @marusak ]

Tooltips:
 - [x] PoC how to dynamically add tooltips
 - [x] Update tooltip when moving within a minute [ @martinpitt ]
 - [ ] *[not MVP? Opinions?]* Custom tooltip implementation to avoid delays and overlapping the graphs, and better formatting

Current state of the art:
![perf](https://user-images.githubusercontent.com/200109/89264547-64bcea80-d633-11ea-9f0d-9d2b7ec5cac8.png)

**Comment by martinpitt** [comment]
@garrett FYI, if you have other things in mind which we need to call the demo "complete enough", please add to the laundry list above.

**Comment by garrett** [comment]
I think the list for the MVP is correct.

Some things I _eventually_ want this to have:
- Top-like top (current system info, not from PCP, so it works for everyone)
- "Upsell" to PCP in place of the graphs, if PCP isn't installed & enabled (as an empty state pattern)
- Scrolling to load more
- Jumping to a specific date/time (would this completely collapse the time between what's seen and where the day starts? or would it do a very high-level, compressed summary of each day/week/month, with expand links to swap out for a detailed view?)

...but I don't think any of these qualify for the MVP. I'm sharing it here, in case anything sparks an idea about what should be on the MVP and also to share the direction I'm thinking this could/should go (eventually).

**Comment by garrett** [comment]
It isn't working properly for me still, even on F32:

![Screenshot_2020-07-29 Performance Graphs - admin localhost localdomain](https://user-images.githubusercontent.com/10246/88821453-f86d6180-d1c2-11ea-91b3-72445ba06936.png)

The page repeats with blank info and the same events again and again too. (You can see this a bit in the screenshot.)

**Comment by martinpitt** [comment]
@garrett : I had this once, but it's a bit hard to reproduce. Minute :30 is exactly when pcp rotates/archives its log, and then somewhere between cockpit-pcp and pcp itself the logs get confused and don't report any real data except for a single number of data. Not earth-shattering for the PoC, but certainly important for the MVP.

**Comment by martinpitt** [comment]
@garrett: This is all fixed in master now.

**Comment by garrett** [comment]
Super cool! I've been testing on several devices and it already works reasonably well. Once we optimize it, it should be super even on those underpowered things.

The test subjects:
- Firefox on my work laptop (ThinkPad T460s) with 20G RAM, not shabby at all
- Firefox on a [Gateway LT2802u](http://www.meetgadget.com/gadget/50696/Gateway+LT2802u), horribly slow netbook from almost a decade ago with 2G RAM and Intel Atom N4551 @ 1.66GHz, running [Endless OS](https://endlessos.com/)
   - FWIW: Endless is a simple GNOME-based desktop geared toward kids and families. (Works well on low-powered devices. Has zram enabled by default and uses ostree on a Debian variant. Self-updates. Supports flatpak and toolbox out of the box too.) 
   - It's the most ChromeOS-like OS based on Free Software.
- Firefox Preview Nightly on a OnePlus 6T
- Chrome on a OnePlus 6T

Everything went pretty well everywhere, except the netbook.

The netbook still worked, but it triggered Firefox's "this page is slow [stop] [wait]" banner. And then scrolling caused a lot of visible repainting. But it's a slow, old laptop. It took around 18 seconds to load.

The phone's browsers both worked amazingly well when loaded. Loading took around 6 - 10 seconds.

I'm sure we'll get the load time down and performance up. This is great with a day's worth of data already. It's quite promising!

**Comment by martinpitt** [comment]
@garrett: I think the empty state for "pcp not enabled" should be part of the MVP, and not hard to do as the Overview page already does it. I created epic tasks for your other points.

**Comment by martinpitt** [comment]
@marusak, @garrett : In commit 46a32d06d5416e67f7af0b0bcb5725b6b9e40947 I merged the util+sat graphs. WDYT?

**Comment by martinpitt** [comment]
@andreasn, @garrett, @marusak: From my POV this is good enough now for a first PoC. The Jira epic has cards for all the subsequent features/steps (such as showing current data, adding integration tests, and eventually integrating this into Cockpit itself). Do you want to give this another try and see if you see some gaping hole still? Feel free to create more issues on this project, of course.
