### ISSUE TITLE
Fix current metrics design issues

### ISSUE THREAD

**Issue by martinpitt** [martinpitt/performance-graphs#31]
- [x] drop left/right padding from "top 5" tables: PR #36 
- [x] hide overflow of long unit names with unbreakable words. PR #36 ; Reproducer:

      sudo systemd-run -p CPUQuota=8% -u calc-harder-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.service dd if=/dev/urandom of=/dev/null
     sudo systemd-run -p CPUQuota=6% -u calc-harder-bbbbbb-ccccccc-ddddddd-eeeeeee-ffffff-gggggg-hhhhhhh-iiiii.service dd if=/dev/urandom of=/dev/null

  and after you are done:
 
      sudo systemctl stop calc-harder-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.service calc-harder-bbbbbb-ccccccc-ddddddd-eeeeeee-ffffff-gggggg-hhhhhhh-iiiii.service

- [x] keep units on the same line as values PR #36
![keepunit](https://user-images.githubusercontent.com/12330670/92469106-8e3dd880-f1d4-11ea-9741-274d37817352.png)

- [ ] Pin the top 5 tables to the card bottom, so that they align vertically: PR #41

- [x] Show load values as proper key/values (needs issue #16 decided and fixed)

**Comment by marusak** [comment]
Another thing would be to keep units on the same line with values:
![keepunit](https://user-images.githubusercontent.com/12330670/92469106-8e3dd880-f1d4-11ea-9741-274d37817352.png)
